## Travis CI configuration for SmartRPyC

branches:
  except:
    - gh-pages

language: python

python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"

env:
    - PIP_USE_MIRRORS=true

script: "python setup.py test"

matrix:
  allow_failures:
    - python: "3.1"
