## Travis CI configuration for xk0/SmartRPyC

branches:
  except:
    - gh-pages

language: python

python:
  - "2.7"

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=pypy

install:
  - pip install tox --use-mirrors

script: tox

after_success:
  - pip install python-coveralls
  - coveralls

matrix:
  allow_failures:
    - env: TOXENV=py31
    - env: TOXENV=pypy
