branches:
  except:
    - gh-pages
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install: "python setup.py install"
script: "python setup.py test"
matrix:
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"
